# Generated by Django 5.0.3 on 2024-03-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Карта товара Муж', 'verbose_name_plural': 'Карты товаров Муж'},
        ),
    ]
