# Generated by Django 5.0.3 on 2024-03-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_womenproduct_delete_productw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/product_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='womenproduct',
            name='image',
            field=models.ImageField(upload_to='static/women_product_images/', verbose_name='Изображение'),
        ),
    ]
