# Generated by Django 5.0.3 on 2024-03-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_newarrivalsproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewArrivalsProducts',
            new_name='NewArrivalsProduct',
        ),
    ]
